"""Fix UserPreferences model

Revision ID: 210c332b16d9
Revises: 6418fe61c2ec
Create Date: 2024-10-20 21:48:57.370905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210c332b16d9'
down_revision = '6418fe61c2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('colors', sa.String(length=255), nullable=True),
    sa.Column('disliked_colors', sa.String(length=255), nullable=True),
    sa.Column('furniture', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('layout', sa.String(length=50), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
